name: 生成 GitHub 動態的蛇蛇動畫

on:
  schedule: # execute every 24 hours
    - cron: "0 14 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: 生成 snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: 將 snake.svg 推送到 snake 分支儲存
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
